#!/usr/bin/env python

from datetime import date
import os
import re
import sys


def print_goals():
    with open(os.path.expanduser("~/.shimei/todo.shimei")) as f:
        lines = f.readlines()
        proj = ""
        for line in lines:
            proj_match = re.search("^\s*\[([a-z]{4})\]", line)
            if proj_match:
                proj = proj_match[1]
                continue

            goal_match = re.search("^\s*! \[([a-z]{4})\](.*)", line)
            if goal_match:
                goal = goal_match[1]
                rest = goal_match[2]
                print(f"[{proj}!{goal}]{rest}")


def open_editor():
    date_string = date.today().strftime("%d-%m-%Y")
    os.system(f"vim \"+syn match currentDate '{date_string}' | hi def link currentDate String\" -O ~/.shimei/log.shimei ~/.shimei/todo.shimei")


def print_help():
    print(
        "Usage:\n"
        "    $ shimei [goals]\n"
        "\n"
        "Examples:\n"
        "    $ shimei\n"
        "        open editor with log and tasks\n"
        "    $ shimei goals\n"
        "        print goals"
    )


def main():
    args = sys.argv[1:]
    if len(args) == 0:
        return open_editor()
    else:
        if args[0] == "goals":
            return print_goals()
    return print_help()


if __name__ == "__main__":
    main()
